### ISSUE TITLE
Purge Cloudflare Cache on deploy

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/destinyitemmanager.com#40]
```
      - name: Purge CloudFlare cache
        run: ./build/purge-cloudflare.sh
        env:
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          APP_DOMAIN: beta.destinyitemmanager.com
``` 
we should do this for the website as well
